api_path: "/Users/runeb/Projects/Underskog/app/controllers/api"
name: "Underskog"
url: "http://underskog.dev"
key: 'voqgUEUrvFt9nR4yYTtUvtMvlatrroLrXEhQ6jnK'
secret: 'dr5tPcfiQEd5zKlIxg76Z0EZjnvBD6vJIsy3jHxP'
